version: '3.9'
services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-markdown}
      POSTGRES_USER: ${POSTGRES_USER:-markdown}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER:-markdown}
      DB_PASSWORD: ${POSTGRES_PASSWORD:-password}
      DB_NAME: ${POSTGRES_DB:-markdown}
      JWT_SECRET: ${JWT_SECRET:-changeme}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET:-changeme2}
    volumes:
      - ./markdown_history:/app/history

  webapp:
    image: nginx:alpine
    depends_on:
      - backend
    volumes:
      - ./webapp/dist:/usr/share/nginx/html:ro
    ports:
      - "80:80"

volumes:
  db_data:
